### ISSUE TITLE
Example for AWS SAM without Typescript

### ISSUE THREAD

**Issue by librarywebchic** [anttiviljami/openapi-backend#117]
I am trying to take the existing example for AWS SAM (https://github.com/anttiviljami/openapi-backend/tree/master/examples/aws-sam) and make it work without Typescript. However, I can't get the tests to pass. I get errors about Async functions not being resolve before timeout. Has anyone else done this or made this work?

**Comment by anttiviljami** [comment]
Hi @librarywebchic. I trust you already found the solution to your problem. :) 

If not, feel free to reopen
