### ISSUE TITLE
Dynamic definitions

### ISSUE THREAD

**Issue by pilotak** [anttiviljami/openapi-backend#125]
Is it possible to load definitions dynamically? i would like to keep the function and definition in one file instead of writing in to `openapi.yml`

`app.ts`
```ts
import OpenAPIBackend from 'openapi-backend';
import * as routes from './routes';

const api = new OpenAPIBackend({ definition: 'magic-here', handlers: routes });
```

`routes/status.ts`
```ts
import { Request, Response } from 'express';
import { Context } from 'openapi-backend';

export const status = async (c: Context, req: Request, res: Response): Promise<Response> => {
  return res.status(200).json({ status: 'OK' });
};

/*
const schema: Operation = {
  path: '/status',
  method: 'get',
  operationId: 'status',
  responses: {
    '200': {
      description: 'OK',
    },
  },
};
*/
```
`routes/index.ts`
```ts
export * from './status';
```

**Comment by elby22** [comment]
@pilotak Not sure what you mean by "dynamically", but you can use an object of type OpenAPIV3.Document as a value for `definition` in the constructor.

**Comment by pilotak** [comment]
i meant similar to this https://github.com/kogosoftwarellc/open-api/blob/aaaad58bcb71e221b9df980248bf79ae08ea55fa/packages/express-openapi/test/sample-projects/basic-usage/api-routes/users.js#L40
