### ISSUE TITLE
Crash on format field

### ISSUE THREAD

**Issue by mnn** [anttiviljami/openapi-backend#13]
[format](https://swagger.io/specification/#dataTypes) doesn't seem to be supported (spec says it can even be an arbitrary string):

    (node:11785) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: unknown format "int64" is used in schema at path "#/properties/path/properties/customerId"

or

    (node:12123) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: unknown format "password" is used in schema at path "#/properties/requestBody/allOf/1/properties/password"

**Comment by anttiviljami** [comment]
Hi! Probably a good idea to ignore unknown formats by default. Right now we are using default Ajv behaviour.

https://ajv.js.org/#formats

Let's add `unknownFormats: 'ignore'` to our default AjvOpts

**Comment by anttiviljami** [comment]
The default behaviour for validation is now to emit a warning when an unknown format is encountered in JSON schema. If you wish to get rid of the warning, you can pass ajvOpts.unknownFormats an array with allowed custom formats.

```javascript
const api = new OpenAPIBackend({
  definition,
  ajvOpts: { unknownFormats: ['myCustomFormat'] },
});
```

**Comment by mnn** [comment]
Damn, that was fast :smiley:.
