### ISSUE TITLE
OpenAPI 3.1 Support

### ISSUE THREAD

**Issue by wszydlak** [anttiviljami/openapi-backend#158]
Hi, OpenAPI 3.1 has been released - https://www.openapis.org/blog/2021/02/18/openapi-specification-3-1-released
It would be nice to bring support of 3.1 to `openapi-backend`.

Here is how to migrate: https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0

Seems there will be some work to be done, but in case of schema validation i've found that `ajv@8` supports latest json schema draft 2020, so this part should not be complicated.

**Comment by anttiviljami** [comment]
@wszydlak agreed.

Anyone willing to look into this, PRs appreciated :)

**Comment by anttiviljami** [comment]
For the new 4.0.0 release of `openapi-backend`, I've upgraded to Ajv@8. Hopefully this helps!

**Comment by wszydlak** [comment]
Open API 3.1 types released: https://github.com/kogosoftwarellc/open-api/pull/757
