### ISSUE TITLE
API for validating data that doesn't originate in an HTTP request

### ISSUE THREAD

**Issue by rhythnic** [anttiviljami/openapi-backend#23]
Firstly, excellent library.  I'm very optimistic about using it.  I am integrating openapi-backend into a application rewrite at work.  I can see how to set up validation for requests, but I would also like to do validation in the model for data that's generated internally, by another microservice, from a websocket connection, etc.  My plan right now is to use ajv and get the schema from the openapi definition.  Since openapi-backend already has the validation functions created for validating request payloads, I think it would be useful to have an API method to expose that validation functionality.  It could accept the operationId and a payload, and return a validation result.

`api.validateOperationBody(operationId, data)`

**Comment by anttiviljami** [comment]
Thanks for bringing this up! Let me just try to understand this.

So you would like to validate some data against an operation's response schema?

There's already [api.validateResponse(res, operation)](https://github.com/anttiviljami/openapi-backend/blob/master/DOCS.md#validateresponseres-operation-statuscode) for validating data. It takes in the operation either as an object or just the operationId as string.

Or if you're looking to validate data against the request payload schema, similarly there's [api.validateRequest(req, operation)](https://github.com/anttiviljami/openapi-backend/blob/master/DOCS.md#validaterequestreq-operation) which works similarly.

Could you re-iterate why those wouldn't work? 

Thanks!

**Comment by rhythnic** [comment]
I overlooked that there is a docs file.  After looking at validateRequest, it might work, as long as it doesn't require anything other than the request body.  I suspect that's the case though, since that would allow invalid requests.  Essentially I'm looking to do validation using the schemas in the openapi definition. So if there were a resource `users`, and the schema to validate the request body for a POST to `/users` were called `userCreate`, to do it without a special API would look like this:

`ajv.validate(definition.components.schemas.userCreate, data)`

If a user were created within the application, and not via a POST, I would use that call to validate the data within the user model.  All-in-all, it's not difficult to do that, which makes me think that to add an API method to openapi-backend isn't really warranted.  But if it were there, I would use it.  I understand though that library maintainers have to guard against API bloat.

**Comment by anttiviljami** [comment]
I think this would fall more on the side of API bloat. Like you mentioned, you can use Ajv to create your own custom validation using schemas in `api.document`

Closing this issue! Feel free to continue this discussion if you have good ideas :)
