### ISSUE TITLE
Restrict to Node 8+ and use native async/await

### ISSUE THREAD

**Issue by devoto13** [anttiviljami/openapi-backend#26]
I would like to restrict the library to support Node 8+ and configure TypeScript to use native `async/await` instead of down leveling it. 

This gives two benefits:
- much more pleasant debugging experience
- smaller library size

Node 6 reaches [end-of-life](https://github.com/nodejs/Release#release-schedule) in April 2019 (~3 months from now), so it may be a good time to drop it.

What do you think?

**Comment by Codermar** [comment]
+1

**Comment by anttiviljami** [comment]
I'm ok with that. Wanna submit a PR? :)

**Comment by devoto13** [comment]
@anttiviljami Yes, will do it.
