### ISSUE TITLE
[Question/Comments] Security Handlers etc.

### ISSUE THREAD

**Issue by Codermar** [anttiviljami/openapi-backend#31]
Hi,
I've been playing with openapi-backend and so far I've found it to be the most complete package to use with OAS. 👍 

I have a few comments/questions 

Security Handlers: I kind of like the way the [swagger-routes-express](https://github.com/davesag/swagger-routes-express#adding-security-handlers) package implements it. How is security handled in openapi-backend?

Mapping to nested API routes in [swagger-routes-express](https://github.com/davesag/swagger-routes-express#mapping-to-nested-api-routes) is also kind of cool.

Even though we can use apiRoot to indicate the matched relative to apiRoot, it is kind of limited right now and it effectively creates two routes, one on the root and one appended to the apiRoot In  swagger-routes-express, I like how you can map your api root by tag. i.e. "root" and the rest will default to the defined  default servers [see here](https://github.com/davesag/swagger-routes-express#openapi-version-3) 

Overall the two packages seem to have quite a bit in common. I would be nice to join forces :-)

**Comment by anttiviljami** [comment]
I'm very interested in implementing security handlers to `openapi-backend`. The design challenge however is that we don't want to do anything that is express-specific, like your example. It needs to be generic.

To your second point about the apiRoot being limited, I'm not sure I understand it. Care to give some example case where openapi-backend would fall short vs swagger-routes-express?

**Comment by FMCorz** [comment]
+1. I'm happy to help if I can. I would suggest that the easier right now is to declare the security handlers and give them enough information about the request to pursue.

For example:
```
const api new APIBackend({
  securityChecks: {
     [name]: (scopes, context, req, res) => false
  },
  handlers: {
     securityFailed: (context, req, res) => {
       res.writeHead(401);
       res.end()
     }
  }
};
```

And with express, you'd still do:
```
app.use((req, res) => {
  api.handleRequest(req, req, res);
});
```

The `securityFailed` handler would default to what is above. While the validation of the spec would fail if a security check is declared but not implemented. The APIBackend would call each securityCheck until one is matched. 

What do you think?

**Comment by Hankrecords** [comment]
I made a pull request with the framework-agnostic solution I implemented in my own project (figured why not make a pull request while I'm at it).
It uses the OpenAPI 3 SecuritySchemaObject definition, so I think it should be pretty solid.
Currently supports only HTTP and apiKey though, because, well, I didn't need the other types lol.
Let me know what you think! I hope it's useful to others.

**Comment by anttiviljami** [comment]
I've had a look at @Hankrecords PR and came to the conclusion that while it's a good start, it's not quite there yet.

Here's my plan to implement auth handling for `openapi-backend`

1. Make global and per-operation [Security Requirement Objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#securityRequirementObject) available on the Context object for each request. Thanks @Hankrecords for this implementation & idea!
2. Add a way to register security handlers for each [Security Scheme Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#security-scheme-object) defined in the API definition. These handlers will then be applied for each request that lists the security scheme in the matched security requirements. The handler's return value provides whether the security check passed and can provide authorisation metadata to the context object for later handlers.
3. Add a generic `unauthorizedHandler` as a catch all to handle non-passing security handlers, again idea from @Hankrecords PR!
4. Provide reference implementations for security handlers that can be easily applied. At least for simple `http` and `apiKey` security schemes.
