### ISSUE TITLE
Separate paths with trailing slash from non-trailing slash paths

### ISSUE THREAD

**Issue by Studnicky-GB** [anttiviljami/openapi-backend#34]
I was working with this lib and noticed that it strips all trailing slash in an attempt to normalize paths.

There's just one problem with that - a trailing slash actually has semantic meaning in REST architecture.

This decision looks very intentional given that regex in the router and there are about four or five tests written to prove that the path matching will ignore trailing slashes, so I wanted to bring it up here as a discussion before issuing a pull request.

Why was this decision made to ignore semantically accurate trailing slashes?

**Comment by Studnicky-GB** [comment]
I am referring specifically to this line here:
https://github.com/anttiviljami/openapi-backend/blob/master/src/router.ts#L157

This decision violates the URI as defined by rfc3986 in the definition of Hierarchical Identifiers:
https://tools.ietf.org/html/rfc3986#section-1.2.3

**Comment by Studnicky-GB** [comment]
In a more specific example:

`GET http://pets/{petid}
`- should return a pet by ID


`GET http://pets/
`- informs the user that they will receive a collection of resources.


`GET http://pets
`- informs the browser user that this endpoint will return a single `pets` resource.  The plural makes it verbally and semantically misleading.

**Comment by anttiviljami** [comment]
Interesting. I've always found stripping trailing slashes as desireable behaviour, as most applications don't differentiate between the two.

Perhaps this should be a configurable behaviour in `OpenAPIRouter`. I would still probably keep the existing behaviour by default, but allow a constructor option to change it.

Is this something you would be interested in working on?

**Comment by Studnicky-GB** [comment]
Would that I had the bandwidth.  Unfortunately quite wrapped up with getting a new project off the ground.

**Comment by anttiviljami** [comment]
Same situation here, unfortunately. :) I'll keep this issue open and see if somebody needs this feature enough to implement a PR.

**Comment by Studnicky-GB** [comment]
Yeah understandable.  I am sacrificing semantic accuracy for now and hope to come back to this soon.

**Comment by anttiviljami** [comment]
This is now possible since `openapi-backend@4.1.0` by setting `ignoreTrailingSlashes: false`:

https://github.com/anttiviljami/openapi-backend/blob/master/DOCS.md#parameter-optsignoretrailingslashes
