### ISSUE TITLE
Incorrect 2.0.0 release on NPM

### ISSUE THREAD

**Issue by devoto13** [anttiviljami/openapi-backend#35]
It looks like the the release 2.0.0 on NPM does not contain the changes from the last merged PRs. Did you forget to `npm run build` before publishing?

**Comment by anttiviljami** [comment]
Ah, must be. Sorry about that. I need to configure auto-publish on new tag in Travis. 

Fixed in release 2.0.1!

**Comment by devoto13** [comment]
No problems. Thanks for the quick fix!
