### ISSUE TITLE
Additional properties in parameters, free form ?

### ISSUE THREAD

**Issue by newza-fullmetal** [anttiviljami/openapi-backend#379]
Hello, 

We are facing a problem with parameters validation. 
We are not sure if we are off standard or not. 

But before using openapi-backend we used express-openapi and it allowed us to let non defined query param without validation. 

Really usefull when using bunch of filters with infinite combination. 

But we are stuck here , we had to override the validationFail handler to still go in the controller if validation fails in query. 
According to openapi spec free form should handle our case but it does not seems to work

Thanks for your help

**Comment by Fetchinator7** [comment]
@newza-fullmetal I'm not sure without an example, but my PR should allow you to set `additionalProperties: true` (or some other schema) on your query parameter to pass validation 😄 .
