### ISSUE TITLE
Typescript types are too loose

### ISSUE THREAD

**Issue by mkrauss** [anttiviljami/openapi-backend#38]
A number of the type definitions are nullable for no reason I can discern. This is forcing me to write code like:

```
if (
  !apiContext ||
  !apiContext.validation ||
  !apiContext.validation.errors ||
  !apiContext.request
) {
  // Return a 500 error which will probably never actually happen
  return
}

// Otherwise continue with the handler
```

This is from a `validationFail` handler, but at least some similar checks might be needed in any handler. Is there any reason these things all need to be nullable?

**Comment by anttiviljami** [comment]
Hi @mkrauss ! Thanks for the feedback. There may well be some definitions where things are unnecessarily left nullable, even though there should never be such a case. 

I'll look into the ones you've pointed out here.

**Comment by ealtunyay** [comment]
For now I'm using this to avoid the conditionals that @mkrauss was using:

```typescript
import { Context } from "openapi-backend";
import { Request, Response} from "express";
import ajv from "ajv";

type ContextWithErrors = Context & {
  validation: { errors: ajv.ErrorObject[] };
};

api.register(
  "validationFail",
  (context: ContextWithErrors, _req: Request, res: Response): void => {
    // Use `context.validation.errors`
  }
);
```
