### ISSUE TITLE
Dereference broken in v2.3.2

### ISSUE THREAD

**Issue by simov** [anttiviljami/openapi-backend#41]
After https://github.com/anttiviljami/openapi-backend/commit/d098d16c6e82ede0fc7240f184c12f53ee4a3fba I can't reference spec files.

My directory structure

```
├── lib
│   ├── index.js
│   └── lambda.js
├── spec
│   ├── lambda.yml
│   └── openapi.yml
├── test
│   └── authorizer.js
└── serverless.yml
```

In `openapi.yml` I have:

```yml
openapi: 3.0.1
info:
  title: lambda-api-name
  version: 1.0.0
paths:
  /thepath:
    $ref: './spec/lambda.yml'
```

And this was kind of weird because the reference was not relative to the `openapi.yml` document, but instead to the project root.

In `index.js` I'm loading the spec like this:

```js
definition: path.resolve(__dirname, '../spec/openapi.yml'),
```

And this setup was working up until v2.3.1

Now I either get:

```
Error opening file "/the-path-to-lambda/spec/spec/lambda.yml"
in node_modules/json-schema-ref-parser/lib/resolvers/file.js:51:20
```

or if I update the reference to `$ref: './lambda.yml'` as it should be, I get:

```
Error opening file "/the-path-to-lambda/lambda.yml
in node_modules/json-schema-ref-parser/lib/resolvers/file.js:51:20
```

So I'm kind of stuck with this, I either have the path doubled `spec/spec` or no path at all.

**Comment by simov** [comment]
> Any chance you could be using swagger-parser somewhere in your project other than openapi-backend?

Yes, I am.

Also the above code is executed inside a spawned process using serverless.

**Comment by anttiviljami** [comment]
Could you make sure the other swagger parser methods are also using the definition using the path and NOT the parsed schema object.

**Comment by simov** [comment]
I was dereferencing the parsed document instead of the spec definition, but that's truly bizarre, is there some state inside the swagger-parser?

**Comment by anttiviljami** [comment]
No and that’s exactly the problem. SwaggerParser  needs the entry file  path for refs to work correctly. Otherwise it will default to using CWD as the base for any refs. . 

Closing this issue now. Let me know if you still need further help and I’ll be glad to help!
