### ISSUE TITLE
Async Security Handlers

### ISSUE THREAD

**Issue by FedeStainless** [anttiviljami/openapi-backend#429]
Hello, thank you for all this effort, this project is amazing. I have an issue I wasn't able to sort out yet.

Using Express:
I have an async process that validates the API Key with another server (which is in the same network), when I use a classic Express middleware I would call `next` in the case of success or `send` in the case of failure.
I've tried creating an async security handler but it is kind of a race condition, so it's already calling the operation.
Is there any way for the security handler to be async or a promise?

Thank you once again.

**Comment by anttiviljami** [comment]
Security handlers are async. Just make the handler function `async` with `await` or return a Promise

**Comment by FedeStainless** [comment]
For the record, the security handler it's working in a counter intuitive way (to me), when I use reject() it allows the user to continue, when I use resolve(), it gives an unauthorized.
```
const snooze = ms => new Promise(resolve => setTimeout(resolve, ms));
api.registerSecurityHandler("sessionTicket", (c) => {
  //const time = 0;
  return new Promise((resolve, reject) => {
    snooze(5000).then(r=>reject());
  });
});
api.register('unauthorizedHandler', (c, req, res) => {
  return res.status(401).json({ err: 'unauthorized' })
});
```

**Comment by anttiviljami** [comment]
@FedeStainless pretty sure that’s not right. please refer to the docs for security handlers. 

> Truthy return values from security handlers are generally interpreted as auth success, unless the return value is an object containing an error property.
> 
> All falsy return values are interpreted as auth fail.
>
> Throwing an error from the security handler also gets interpreted as auth fail. The error is available in context.security[name].error.

Maybe also check your security configuration in the openapi definition, are multiple security schemes allowed?

**Comment by anttiviljami** [comment]
See: https://github.com/anttiviljami/openapi-backend/blob/d19b708d9cc84be1fb25e12e24c2be0cdb43afd5/src/backend.test.ts#L286

**Comment by FedeStainless** [comment]
Is the only security schema, and my test was keeping the same openapi document and just changing resolve to reject back and forth. 
If I use a non-promise it works, but with async or promise is not working for me.
I don't see any tests for an async security handler.
I will use it "reversed"... but I don't know what am I doing wrong.

**Comment by anttiviljami** [comment]
What value did you resolve the async securityHandler promise with? Resolve with falsy value is treated as auth failure.

**Comment by FedeStainless** [comment]
That was the issue! resolve() ===> falsy
reject() ===> truthy? :P
using resolve(true) and resolve(false) works

**Comment by anttiviljami** [comment]
Right! Rejecting with an empty value (no error) is actually treated as auth pass. That’s a bug!

**Comment by anttiviljami** [comment]
https://github.com/anttiviljami/openapi-backend/blob/d19b708d9cc84be1fb25e12e24c2be0cdb43afd5/src/backend.ts#L336

**Comment by FedeStainless** [comment]
I wasn't that off. Thank you for the help! Enjoy your weekend :)
