### ISSUE TITLE
Paths should not match at / when apiRoot is set

### ISSUE THREAD

**Issue by FMCorz** [anttiviljami/openapi-backend#44]
The router does not enforce the presence of the `apiRoot` when matching the request with a route. For example, with `apiRoot` set to `/v1` both requests `/v1/my/operation` and `/my/operation` will call the handler.

Prior to normalizing the path, the router should ensure that the prefix is found.

**Comment by anttiviljami** [comment]
Seems like a bug. Want to have a look? Currently busy with client work, unfortunately so might take me a bit to get around to this.

**Comment by FMCorz** [comment]
Same here, but I'll try. Meanwhile I use this workaround:

```
app.use((req, res, next) => {
    if (!req.path.startsWith('/v1/')) {
      return next(new NotFoundError());
    }
    api.handleRequest(req, req, res, next);
  };
```
