### ISSUE TITLE
[Question] Automatically cleaning up values in postResponseHandler

### ISSUE THREAD

**Issue by FMCorz** [anttiviljami/openapi-backend#45]
Would you be able to recommend a method to effectively clean the response values using the schema? I would like to validate that a) the response is correct, b) the additional properties that would be present in the response are stripped.

I know that a) can already be handled. I'm just unsure how to proceed with B as I'd rather avoid building my own mechanism for cleaning up values based on the operation's response schema.

Thanks!

**Comment by anttiviljami** [comment]
For a), see the docs for [Response Validation](https://github.com/anttiviljami/openapi-backend/blob/master/README.md#response-validation)

For b), i.e. sanitizing response values, this is slightly more complicated. You would need to build something custom that recursively walks through the response object and strips any any additional properties. I'm not aware of anything that would readily be able to do that.

Closing this issue now. Sorry it took me so long to respond!
