### ISSUE TITLE
Update openapi-types to ^12.0.2 to fix TypeScript 4.8 build issues

### ISSUE THREAD

**Issue by johannes-wtfoxtrot** [anttiviljami/openapi-backend#465]
As described in https://github.com/kogosoftwarellc/open-api/issues/829 TypeScript 4.8 builds fail due to a bug in the openapi-types package.

The issue is fixed in ^12.0.2, but the currently pinned version is ^10.0.0.

It would be great to have the version updated in order to pass the fix down.

Until then one can switch to the new package by
```
  "resolutions": {
    "openapi-types": "^12.0.2"
  },
```

**Comment by anttiviljami** [comment]
Hi @johannes-wtfoxtrot. Just released `openapi-backend@5.6.0` with `openapi-types@^12.0.2`. ✅
