### ISSUE TITLE
Request object in context contains correct parameters, request object passed as second parameters does not contain parameters

### ISSUE THREAD

**Issue by rageycomma** [anttiviljami/openapi-backend#48]
Say if you have an OpenAPI specification:
```yaml
/my/path/{id}:
 operationID: myPathById
 ... etc
```
And then have this callback: 
```typescript
export async function myPathById(context: Context, request: Request, response: Response) {
 // context.request.params contains "id" = ...
 // request.params does not contain "id".
}
```

The "request" object doesn't have the parameters in it, but the context does -- shouldn't these be consistent? 

Thanks :)

**Comment by anttiviljami** [comment]
In addition to the context object; the handler receives whatever raw args you pass to .handleRequest

If you’re using express and pass the req and res as arguments, that’s exactly what the handler will see.
