### ISSUE TITLE
Accessing default value of a openAPI query propterty

### ISSUE THREAD

**Issue by RoniFinTech2** [anttiviljami/openapi-backend#488]
### Discussed in https://github.com/anttiviljami/openapi-backend/discussions/314

<div type='discussions-op-text'>

<sup>Originally posted by **aschuste** February  7, 2022</sup>
Hi,

ist there a way to get the default value assigend to a query parameter from the openapi.yaml file?
I didn't found a way to acess this value defined in the openapi.ymal inside the openapi-backen.

Example:
```yaml
# ...
paths:
  /api/asset:
    get:
      operationId: assetGet
      parameters:
        - ref: '#/compnents/parameters/Summary'
      responses:
        '200':
          # ...
        '4XX':
          # ...
# ...
components:
  parameters:
    Summary:
      name: summary
      in: query
      description: Is summary=true, only the summary is dipslay instead of detailed view
      required: false
      schema:
        type: boolean
        default: true
```

How to get the default inside the handler? 
If I'm  requesting `GET /api/asset` there is no summary availabel. Neither on `c.request.query` or on `c.request.params`.
If I use `GET /api/asset?summary=false`, I'm getting this value via `c.request.query.summary` as ecpected.

Regards,
Andreas</div>

**Comment by anttiviljami** [comment]
See `context.operation` https://github.com/anttiviljami/openapi-backend/blob/master/DOCS.md#context-object
