### ISSUE TITLE
express-typescript fails with strict mode on

### ISSUE THREAD

**Issue by eiabea** [anttiviljami/openapi-backend#49]
The example only works if the strict mode is set to _false_ in the tsconfig.json file. The main error i ran into is:

```
index.ts:63:41 - error TS2345: Argument of type 'import("/tmp/openapi-backend/examples/express-typescript/node_modules/@types/express-serve-static-core/index").Request' is not assignable to parameter of type 'import("/tmp/openapi-backend/examples/express-typescript/node_modules/openapi-backend/router").Request'.
  Types of property 'headers' are incompatible.
    Type 'IncomingHttpHeaders' is not assignable to type '{ [key: string]: string | string[]; }'.
      Index signatures are incompatible.
        Type 'string | string[] | undefined' is not assignable to type 'string | string[]'.
          Type 'undefined' is not assignable to type 'string | string[]'.

app.use((req, res) => api.handleRequest(req, req, res));
```

I tried to find a workaround other than disabling the strict mode, but without any success. Maybe this issue is related to #38

**Comment by anttiviljami** [comment]
You should be able to work around this issue by casting your headers to the correct type.

Not tested, but should work like this:

```typescript
app.use((req, res) => api.handleRequest({
  ...req,
  headers: req.headers as  as { [key: string]: string },
}, req, res));
```

**Comment by anttiviljami** [comment]
Or alternatively, perhaps more clean solution:

```typescript
import { Request } from 'openapi-backend';
app.use((req, res) => api.handleRequest(req as Request, req, res));
```

**Comment by anttiviljami** [comment]
The issue seems to be that in strict mode, IncomingHttpHeaders is possibly undefined.

You could also just add a check before calling api.handleRequest to make sure headers is populated.

```typescript
app.use((req, res) => {
  if (req.headers === undefined) {
    // should never happen
    throw new Error('Invalid request object');
  }
  return api.handleRequest(req, req, res);
});
```

**Comment by eiabea** [comment]
> Or alternatively, perhaps more clean solution:
> 
> ```ts
> import { Request } from 'openapi-backend';
> app.use((req, res) => api.handleRequest(req as Request, req, res));
> ```

I used this solution, thank you for your help :slightly_smiling_face:
