### ISSUE TITLE
must have required property 'requestBody'

### ISSUE THREAD

**Issue by MinDBreaK** [anttiviljami/openapi-backend#550]
Hello, 

I'm currently trying to add a POST operation with a JSON body. When submitting the request, I receive the following response : 
```json 
{
  "message": [
    {
      "instancePath": "",
      "schemaPath": "#/required",
      "keyword": "required",
      "params": {
        "missingProperty": "requestBody"
      },
      "message": "must have required property 'requestBody'"
    }
  ]
}
```

The operation is defined as following : 
```json
{
  "post": {
    "description": "Create a Camera",
    "operationId": "postCameraList",
    "tags": [
      "Camera"
    ],
    "requestBody": {
      "description": "The camera to create",
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/Camera"
          }
        }
      }
    }
  }
}
```

I'm using an OpenAPIV3 version and submitting requests through SwaggerUI.
Am I missing something or does this belong to a dependent library ? 

I'm using `openapi-backend` with version `5.9.1`. 

I can give more info if necessary.

**Comment by MinDBreaK** [comment]
Yes, so it appears that I was missing the JSON parser for the body. My bad. I though it was already enabled because another part of the server was working fine, but it was because it enabled it on it's own.

I'll be closing this issue then ! 
Thank you for your quick answer though, it sent me on the right path ! Sorry for the false alert

**Comment by ilomon10** [comment]
how do you solve this?
