### ISSUE TITLE
Default value in parameter are not assign when the parameter is missing 

### ISSUE THREAD

**Issue by frogburger** [anttiviljami/openapi-backend#562]
In a parameter, if a default value is defined, the parameter should be assigned to that value when not added to the request. 
I am using openAPI-backend 5.9.1

**Comment by anttiviljami** [comment]
I don’t think I agree with this. Handling inputs, including setting default values should be handled in the operation handler implementation. OpenAPI Backend is agnostic with how parametes should be handled

Happy to hear further arguments for / against.
