### ISSUE TITLE
QUESTION: What's the best way to handle API versioning?  Etherpad

### ISSUE THREAD

**Issue by JohnMcLear** [anttiviljami/openapi-backend#70]
We're looking to start using this module in Etherpad, we're currently using node-express-swagger and that is not well maintained.  Would someone from this project be interesting in working with us to do the integration (compensation is available).  Ideally someone with express and openapi-backend knowledge :)

In Etherpad we have a Base API (v1) then as we added new/modified calls our API version increased.  See https://github.com/ether/etherpad-lite/blob/develop/src/node/handler/APIHandler.js#L47 for code.

I looked to have multiple definition objects but that didn't work.  I read through the docs and I must be going blind because I just can't see how I should set this up..  Really sorry, I'm sure this must be user error!

**Comment by anttiviljami** [comment]
Hi! I'm not 100% sure what you're trying to achieve here with openapi-backend, but maybe I can help.

From your code it looks like you want to validate for a given API version, whether an operation is registered and whether the API version exists.

I would guess you have two approaches to achieve this:

1. Do these checks in your catchall-handler before passing to `api.handleRequest()`
1. Create instances of OpenAPIBackend for each api version with their definition and let the `notFound` and `notImplemented` handlers do the work for you. Then just use the correct instance to pass to `api.handleRequest()`

Let me know if I haven't understood the problem correctly.

**Comment by JohnMcLear** [comment]
Do you have an example of either of these use cases I can refer to?  Just don't wanna re-invent the wheel if such examples exist :)

**Comment by anttiviljami** [comment]
Unfortunately I don't know of any implementations similar to your use case. So far for versioning, we've just incremented the version number in the info section and left it up to the clients to decide what to do when the API version number changes.

**Comment by JohnMcLear** [comment]
@anttiviljami Any chance I can compensate you for your time to create a few examples?  I want to make sure whatever implementation we do is supported moving forward.

**Comment by anttiviljami** [comment]
Sure! Here's my calendly link. Let's have a quick chat to see how I can help.

https://calendly.com/viljami

**Comment by JohnMcLear** [comment]
Prepping notes here: http://video.etherpad.com/p/viljami <http://video.etherpad.com/p/viljami> 



Video call will be there.







-----Original message-----

**Comment by anttiviljami** [comment]
I've added documentation with an example of how to do URI versioning with `openapi-backend`:

https://github.com/anttiviljami/openapi-backend/blob/master/DOCS.md#api-versioning
