### ISSUE TITLE
Handling of errors (exceptions) within operation handlers

### ISSUE THREAD

**Issue by J-O-P** [anttiviljami/openapi-backend#88]
I am wondering how the handling of exceptions should be done for exceptions that could happen within operations handlers. Can't find anything in the documentation or the examples. Is it: 

(A) Every operation handler is supposed to implement its own error handling.

(B) I would like to have exceptions from whitin the operations handler get caught in handleRequest(), stored in the context and then passed to the postResponseHandler (or an dedicated error handler). Here the error could be properly logged and clean a (status 500) response could be sent to the client.

(C) Is the idea to use another mechanism which I did not understand? 

Thanks for your thoughts.

**Comment by anttiviljami** [comment]
Hi! I've designed the library to be agnostic towards error handling. You can perform exception handling either within the operation handlers or simply catch from `handleRequest`.

I always end up doing something like this:

```javascript
try {
  const response = await api.handleRequest();
  return response;
} catch (err) {
  return responseFromError(err);
}
```

**Comment by J-O-P** [comment]
Thanks. I did exactly this in my fork of the library.
